#assg:2==set operations
A=set([1,2,3,4]);
B=set([1,3,4,5,6,7,8]);
print("set A:")
print(A)
print("length of set A=")
print(len(A))
print("set B:")
print(B)
print("length of set B=")
print(len(B))
print("union of set==")
print(A.union(B))
print("intersection of set==")
print(A.intersection(B))
print("difference ==")
print(A-B)
print("symmetric difference==")
print(A^B)
print("difference ==")
print(B-A)
